const { PrismaClient } = require('@prisma/client');
const fs = require('fs');

const prisma = new PrismaClient();

async function restore() {
  // IMPORTANT: Ensure this matches the exact filename generated by your backup script
  const rawData = fs.readFileSync('full_database_backup.json', 'utf8');
  const backup = JSON.parse(rawData);
  const tables = backup.tables;

  console.log('--- 📥 Starting Database Restoration 📥 ---');

  /**
   * TOPOLOGICAL SORT ORDER:
   * Tables are strictly ordered so that independent tables (like users)
   * are restored before tables that depend on them (like articles).
   */
  const orderedTables = [
    // --- LEVEL 0: Independent Tables ---
    { key: 'admin_dashboard', model: 'adminDashboard' },
    { key: 'ai_config', model: 'aiConfig' },
    { key: 'trending_topics', model: 'trendingTopic' },
    { key: 'offers', model: 'offer' },
    { key: 'scraping_sources', model: 'scrapingSource' },
    { key: 'scraping_sessions', model: 'scrapingSession' },
    { key: 'users', model: 'user' },

    // --- LEVEL 1: First-Degree Dependencies ---
    { key: 'articles', model: 'article' },
    { key: 'follows', model: 'follow' },
    { key: 'messages', model: 'message' },
    { key: 'user_stats', model: 'userStats' },
    { key: 'banned_users', model: 'bannedUser' },
    { key: 'audit_logs', model: 'auditLog' },
    { key: 'stories', model: 'story' },
    { key: 'subscriptions', model: 'subscription' },
    { key: 'scraping_logs', model: 'scrapingLog' },
    { key: 'scraped_articles', model: 'scrapedArticle' },
    { key: 'keyword_scraping_stats', model: 'keywordScrapingStats' },
    { key: 'wordpress_connections', model: 'wordPressConnection' },

    // --- LEVEL 2: Second-Degree Dependencies ---
    { key: 'article_ratings', model: 'articleRating' },
    { key: 'article_shares', model: 'articleShare' },
    { key: 'saved_articles', model: 'savedArticle' },
    { key: 'read_history', model: 'readHistory' },
    { key: 'notifications', model: 'notification' },
    { key: 'reported_articles', model: 'reportedArticle' },
    { key: 'ai_article_logs', model: 'ai_article_logs' },
    { key: 'wordpress_publish_jobs', model: 'wordPressPublishJob' },
    
    // Comments go last due to self-referencing (replies to comments)
    { key: 'comments', model: 'comment' } 
  ];

  try {
    for (const item of orderedTables) {
      let dataToInsert = tables[item.key];

      if (dataToInsert && dataToInsert.length > 0) {
        console.log(`📦 Restoring: ${item.key} (${dataToInsert.length} records)...`);

        // 1. Special handling for self-referential comments
        if (item.key === 'comments') {
          // Sort so root comments (parentId = null) are inserted before replies
          dataToInsert = dataToInsert.sort((a, b) => {
            if (!a.parentId && b.parentId) return -1;
            if (a.parentId && !b.parentId) return 1;
            return new Date(a.createdAt) - new Date(b.createdAt);
          });
        }

        // 2. Special handling for ai_article_logs schema mapping
        if (item.key === 'ai_article_logs') {
          dataToInsert = dataToInsert.map(log => {
            // Destructure to remove the raw database column name
            const { savedToDraftId, ...rest } = log; 
            return {
              ...rest,
              // Map the value back to the Prisma Client property name
              linkedArticleId: savedToDraftId 
            };
          });
        }

        await prisma[item.model].createMany({
          data: dataToInsert,
          skipDuplicates: true // Prevents crashes if records already exist
        });
      }
    }

    console.log('\n' + '⭐'.repeat(20));
    console.log('✅ DATABASE FULLY RESTORED');
    console.log('⭐'.repeat(20));

  } catch (error) {
    console.error('\n❌ RESTORE FAILED:', error);
  } finally {
    await prisma.$disconnect();
    console.log('--- Database Connection Closed ---');
  }
}

restore();