/**
 * MASTER KEYWORD LIST
 *
 * This is the predefined keyword list passed to the AI for subtopic matching.
 * Keywords are general enough to apply across topics, but specific enough
 * to serve as meaningful article subtopics.
 *
 * The AI receives this full list and selects 5–10 that best match
 * the user's prompt topic. The AI never invents new keywords.
 *
 * To add new keywords: just add strings to the array below.
 * This list is loaded once when the server starts and kept in memory.
 *
 * Total keywords: ~400
 * Coverage: Technology, Business, Health, Environment, Education, Science,
 *           Society, Finance, Travel, Food, Sports, History, Politics, Arts,
 *           Literature, Entertainment, Lifestyle, Hobbies, Agriculture,
 *           Industries, Religion & Beliefs, Career, Relationships, Humor,
 *           and more.
 */

const KEYWORD_LIST = [

  // ─── Technology & Digital Life ───────────────────────────────────────────
  "Artificial intelligence",
  "Machine learning",
  "Robotics",
  "Cybersecurity",
  "Internet and networking",
  "Social media platforms",
  "Mobile technology",
  "Gaming and video games",
  "Software and apps",
  "Cloud services",
  "Digital privacy",
  "Online safety",
  "Tech gadgets",
  "Electric vehicles",
  "Space technology",
  "Emerging technologies",
  "Automation and jobs",
  "Digital transformation",
  "Streaming and media",
  "Smart home technology",

  // ─── Business & Entrepreneurship ─────────────────────────────────────────
  "Entrepreneurship",
  "Starting a business",
  "Small business",
  "Corporate world",
  "Remote work",
  "Leadership",
  "Team management",
  "Marketing and advertising",
  "E-commerce",
  "Customer service",
  "Business strategy",
  "Workplace culture",
  "Networking and connections",
  "Freelancing",
  "Side hustles",
  "Supply chain and logistics",
  "Global trade",
  "Economic trends",
  "Business ethics",
  "Productivity at work",

  // ─── Finance & Money ─────────────────────────────────────────────────────
  "Personal finance",
  "Budgeting",
  "Saving and investing",
  "Stock market",
  "Real estate",
  "Retirement planning",
  "Debt and credit",
  "Cryptocurrency",
  "Banking and loans",
  "Insurance",
  "Taxes",
  "Financial independence",
  "Passive income",
  "Wealth building",
  "Cost of living",
  "Consumer spending",
  "Economic inequality",
  "Government spending",
  "Global economy",
  "Financial literacy",

  // ─── Health & Medicine ───────────────────────────────────────────────────
  "Mental health",
  "Physical fitness",
  "Nutrition and diet",
  "Sleep and rest",
  "Stress and anxiety",
  "Chronic diseases",
  "Women's health",
  "Men's health",
  "Children's health",
  "Preventive health",
  "Healthcare systems",
  "Hospitals and clinics",
  "Medical research",
  "Medicines and drugs",
  "Surgery and treatments",
  "Alternative and natural medicine",
  "Aging and elderly care",
  "Addiction and recovery",
  "Disability and accessibility",
  "Public health",

  // ─── Wellness & Personal Growth ──────────────────────────────────────────
  "Mindfulness and meditation",
  "Self-improvement",
  "Goal setting",
  "Habits and routines",
  "Emotional intelligence",
  "Confidence and self-esteem",
  "Motivation and inspiration",
  "Life coaching",
  "Dealing with failure",
  "Overcoming challenges",
  "Finding purpose",
  "Positivity and gratitude",
  "Simplifying life",
  "Work-life balance",
  "Managing emotions",
  "Building resilience",
  "Time management",
  "Decision making",
  "Boundaries and self-care",
  "Inner peace",

  // ─── Relationships & Family ───────────────────────────────────────────────
  "Romantic relationships",
  "Dating and courtship",
  "Marriage and partnerships",
  "Divorce and separation",
  "Parenting",
  "Raising children",
  "Family dynamics",
  "Friendships",
  "Social skills",
  "Communication in relationships",
  "Conflict resolution",
  "Loneliness and connection",
  "Love and affection",
  "Toxic relationships",
  "Support systems",
  "Elder care",
  "Single life",
  "Blended families",
  "Cultural expectations in families",
  "Grief and loss",

  // ─── Education & Learning ─────────────────────────────────────────────────
  "School and schooling",
  "Higher education",
  "Online learning",
  "Lifelong learning",
  "Study skills and tips",
  "Parenting and education",
  "Teaching and teachers",
  "Learning challenges",
  "STEM subjects",
  "Arts and humanities education",
  "Vocational and trade training",
  "Early childhood learning",
  "Global education",
  "Exams and assessments",
  "School systems",
  "Access to education",
  "Critical thinking",
  "Reading and writing skills",
  "Student life",
  "Academic research",

  // ─── Environment & Nature ─────────────────────────────────────────────────
  "Climate change",
  "Renewable energy",
  "Pollution and waste",
  "Forests and wildlife",
  "Ocean and marine life",
  "Biodiversity",
  "Sustainable living",
  "Green energy",
  "Environmental activism",
  "Natural disasters",
  "Water and sanitation",
  "Plastic and recycling",
  "Farming and land use",
  "Urban green spaces",
  "Animal welfare",
  "Eco-friendly habits",
  "Environmental policy",
  "Air and water quality",
  "Endangered species",
  "Weather and seasons",

  // ─── Food & Cooking ───────────────────────────────────────────────────────
  "Cooking and recipes",
  "Baking",
  "World cuisines",
  "Street food",
  "Healthy eating",
  "Vegetarian and vegan food",
  "Food culture and traditions",
  "Restaurant dining",
  "Food and nutrition",
  "Meal planning",
  "Food history",
  "Drinks and beverages",
  "Wine and spirits",
  "Coffee culture",
  "Food business",
  "Food safety",
  "Farming and food production",
  "Comfort food",
  "Diets and food trends",
  "Food photography",

  // ─── Travel & Places ──────────────────────────────────────────────────────
  "Travel experiences",
  "Budget travel",
  "Luxury travel",
  "Solo travel",
  "Family travel",
  "Adventure travel",
  "Cultural tourism",
  "Travel tips and planning",
  "Tourist destinations",
  "Road trips",
  "Travel photography",
  "Languages and communication abroad",
  "Living abroad",
  "Immigration and relocation",
  "Island and beach destinations",
  "Mountain and nature travel",
  "City travel and urban exploration",
  "Travel and health",
  "Sustainable travel",
  "Hidden gems and off the beaten path",

  // ─── Lifestyle & Home ─────────────────────────────────────────────────────
  "Home decor and design",
  "Minimalism and decluttering",
  "Home organization",
  "DIY and home improvement",
  "Gardening",
  "Fashion and style",
  "Beauty and skincare",
  "Hair care",
  "Luxury and indulgence",
  "Sustainable lifestyle",
  "Morning and evening routines",
  "Pets and animal companionship",
  "Neighborhood and community life",
  "Renting vs owning a home",
  "Interior design",
  "Seasonal living",
  "Outdoor living",
  "Decluttering and organizing",
  "Sleep and bedroom habits",
  "Digital detox and screen time",

  // ─── Hobbies & Interests ──────────────────────────────────────────────────
  "Reading and book clubs",
  "Writing as a hobby",
  "Photography",
  "Painting and drawing",
  "Crafts and DIY projects",
  "Knitting and sewing",
  "Collecting and collections",
  "Board games and puzzles",
  "Music and instruments",
  "Singing and performance",
  "Dancing",
  "Hiking and outdoor recreation",
  "Cycling",
  "Fishing and hunting",
  "Gardening as a hobby",
  "Astronomy and stargazing",
  "Chess and strategy games",
  "Volunteering and giving back",
  "Bird watching and nature observation",
  "Cooking as a hobby",

  // ─── Sports & Athletics ───────────────────────────────────────────────────
  "Football (soccer)",
  "Cricket",
  "Basketball",
  "Tennis",
  "Athletics and track",
  "Swimming",
  "Cycling as a sport",
  "Boxing and combat sports",
  "Rugby",
  "Baseball",
  "Olympic sports",
  "Women in sports",
  "Youth sports",
  "Sports coaching",
  "Sports injuries and recovery",
  "Fitness and gym culture",
  "Sports business and money",
  "Extreme and adventure sports",
  "E-sports and gaming competitions",
  "Fan culture and sports communities",

  // ─── Arts, Culture & Entertainment ───────────────────────────────────────
  "Movies and film",
  "Television and streaming shows",
  "Music and music industry",
  "Theater and performing arts",
  "Visual arts and painting",
  "Photography as art",
  "Fashion as art",
  "Architecture and design",
  "Dance and movement",
  "Museums and galleries",
  "Pop culture",
  "Celebrity culture",
  "Awards and entertainment events",
  "Comedy and humor",
  "Satire and social commentary",
  "Podcasts and audio content",
  "Animation and cartoons",
  "Street art and graffiti",
  "Cultural festivals and events",
  "Fan communities and fandom",

  // ─── Literature & Writing ─────────────────────────────────────────────────
  "Classic literature",
  "Contemporary fiction",
  "Poetry",
  "Short stories",
  "Biographies and memoirs",
  "Storytelling",
  "The writing process",
  "Book reviews",
  "Genre fiction (mystery, fantasy, sci-fi)",
  "Children's literature",
  "Publishing and the book industry",
  "Reading habits",
  "Libraries",
  "Journalism and media writing",
  "Blogging and content creation",
  "Creative nonfiction",
  "Language and linguistics",
  "Translation and multilingual writing",
  "World literature",
  "Mythology and folklore",

  // ─── History ──────────────────────────────────────────────────────────────
  "Ancient civilizations",
  "World wars",
  "Colonial history",
  "Political revolutions",
  "History of science and technology",
  "Social movements in history",
  "Women in history",
  "History of religion",
  "Economic history",
  "Cultural history",
  "Historical figures and leaders",
  "Military history",
  "History of art",
  "History of medicine",
  "Archaeology and ancient discoveries",
  "Historical events and turning points",
  "National histories",
  "Oral history and traditions",
  "Cold War and modern history",
  "History of everyday life",

  // ─── Politics & Society ───────────────────────────────────────────────────
  "Government and governance",
  "Democracy and elections",
  "Human rights",
  "Social justice",
  "Gender equality",
  "Racial equality and diversity",
  "Immigration and refugee issues",
  "Law and justice systems",
  "Public policy",
  "War and conflict",
  "International relations",
  "Political movements",
  "Freedom of speech",
  "Civil society and activism",
  "Poverty and inequality",
  "Community and local politics",
  "Youth and politics",
  "Corruption and accountability",
  "Media and politics",
  "Globalization",

  // ─── Religion, Philosophy & Beliefs ──────────────────────────────────────
  "World religions",
  "Christianity",
  "Islam",
  "Hinduism",
  "Buddhism",
  "Judaism",
  "Spirituality and faith",
  "Religious practices and rituals",
  "Ethics and morality",
  "Philosophy of life",
  "Meaning and purpose",
  "Tradition and culture",
  "Interfaith dialogue",
  "Secularism and atheism",
  "Superstition and folklore",
  "Astrology and belief systems",
  "Mindfulness and Eastern philosophy",
  "Death, afterlife and beliefs",
  "Religion in society",
  "Moral dilemmas",

  // ─── Science & Discovery ──────────────────────────────────────────────────
  "Space and astronomy",
  "Physics",
  "Biology and life sciences",
  "Chemistry",
  "Genetics and DNA",
  "Human body and anatomy",
  "Evolution",
  "Neuroscience and the brain",
  "Ecology and ecosystems",
  "Geology and earth science",
  "Marine science",
  "Mathematics",
  "Scientific discoveries",
  "Science history",
  "Science and society",
  "Research and experiments",
  "Animal behavior",
  "Plant science and botany",
  "Psychology",
  "Anthropology and human origins",

  // ─── Career & Professional Life ───────────────────────────────────────────
  "Job searching",
  "Resume and interviews",
  "Career planning",
  "Changing careers",
  "Workplace challenges",
  "Professional development",
  "Salary and negotiation",
  "Work stress and burnout",
  "Career in tech",
  "Creative careers",
  "Careers in healthcare",
  "Careers in education",
  "Women in the workplace",
  "Workplace diversity and inclusion",
  "Mentorship",
  "Job satisfaction",
  "Gig economy and contract work",
  "Retirement from work",
  "Careers in arts and media",
  "Skills for the future",

  // ─── Agriculture & Rural Life ─────────────────────────────────────────────
  "Farming and agriculture",
  "Organic farming",
  "Rural life and communities",
  "Livestock and animal farming",
  "Crop growing",
  "Sustainable farming",
  "Food production and supply",
  "Farm to table",
  "Agricultural technology",
  "Fishing and fisheries",
  "Beekeeping",
  "Water and irrigation",
  "Agricultural business",
  "Weather and farming",
  "Soil and land health",
  "Traditional farming practices",
  "Food security",
  "Urban farming",
  "Forestry and timber",
  "Agricultural policy",

  // ─── Industries & Services ────────────────────────────────────────────────
  "Healthcare industry",
  "Education industry",
  "Tourism and hospitality",
  "Retail and shopping",
  "Media and entertainment industry",
  "Construction and real estate",
  "Transportation",
  "Energy and utilities",
  "Manufacturing",
  "Finance and banking",
  "Food and beverage industry",
  "Fashion industry",
  "Advertising and PR",
  "Legal services",
  "Non-profits and charity work",
  "Government and public services",
  "Technology industry",
  "Sports industry",
  "Art and creative industries",
  "Telecommunications",

  // ─── Community & Social Issues ────────────────────────────────────────────
  "Community building",
  "Volunteering",
  "Charity and giving",
  "Social media and society",
  "Online communities",
  "Urban life",
  "Rural communities",
  "Youth culture",
  "Generational differences",
  "Aging society",
  "Homelessness and poverty",
  "Mental health in society",
  "Drug and alcohol issues",
  "Crime and safety",
  "Neighborliness and local life",
  "Cultural diversity",
  "Integration and belonging",
  "Identity and self-expression",
  "Protest and activism",
  "Civic engagement",

];

module.exports = KEYWORD_LIST;