/**
 * MASTER KEYWORD LIST
 *
 * This is the predefined keyword list passed to the AI for subtopic matching.
 * Keywords are general enough to apply across topics, but specific enough
 * to serve as meaningful article subtopics.
 *
 * The AI receives this full list and selects 5–10 that best match
 * the user's prompt topic. The AI never invents new keywords.
 *
 * To add new keywords: just add strings to the array below.
 * This list is loaded once when the server starts and kept in memory.
 */

const KEYWORD_LIST = [
  // Technology & AI
  "Artificial intelligence",
  "Machine learning",
  "Deep learning",
  "Neural networks",
  "Natural language processing",
  "Computer vision",
  "Robotics",
  "Automation",
  "Data science",
  "Big data",
  "Cloud computing",
  "Cybersecurity",
  "Blockchain",
  "Internet of Things",
  "Augmented reality",
  "Virtual reality",
  "Quantum computing",
  "Software development",
  "Open source",
  "Algorithm design",

  // Business & Economics
  "Entrepreneurship",
  "Startup culture",
  "Digital marketing",
  "E-commerce",
  "Supply chain",
  "Remote work",
  "Leadership skills",
  "Team management",
  "Financial planning",
  "Investment strategies",
  "Market trends",
  "Brand building",
  "Customer experience",
  "Business strategy",
  "Productivity tools",
  "Work-life balance",
  "Freelancing",
  "Corporate culture",
  "Economic policy",
  "Global trade",

  // Health & Wellness
  "Mental health",
  "Physical fitness",
  "Nutrition",
  "Sleep science",
  "Stress management",
  "Mindfulness",
  "Preventive healthcare",
  "Chronic illness",
  "Medical technology",
  "Telemedicine",
  "Public health",
  "Diet and lifestyle",
  "Exercise science",
  "Healthcare systems",
  "Medical research",
  "Alternative medicine",
  "Aging and longevity",
  "Genetic research",
  "Vaccine development",
  "Mental resilience",

  // Environment & Sustainability
  "Climate change",
  "Renewable energy",
  "Carbon footprint",
  "Sustainable living",
  "Conservation",
  "Ocean health",
  "Deforestation",
  "Green technology",
  "Circular economy",
  "Biodiversity",
  "Air quality",
  "Water management",
  "Eco-friendly products",
  "Urban sustainability",
  "Agricultural practices",
  "Zero waste",
  "Solar energy",
  "Wind energy",
  "Electric vehicles",
  "Environmental policy",

  // Education & Learning
  "Online learning",
  "STEM education",
  "Critical thinking",
  "Lifelong learning",
  "Educational technology",
  "Curriculum design",
  "Student motivation",
  "Higher education",
  "Skill development",
  "Literacy",
  "Early childhood education",
  "Learning disabilities",
  "Teacher training",
  "Global education",
  "Study techniques",
  "Scholarship access",
  "Homeschooling",
  "Vocational training",
  "Creative learning",
  "Academic research",

  // Science & Innovation
  "Space exploration",
  "Physics research",
  "Biology breakthroughs",
  "Chemistry discoveries",
  "Nanotechnology",
  "Genomics",
  "Marine biology",
  "Astronomy",
  "Materials science",
  "Particle physics",
  "Neuroscience",
  "Scientific method",
  "Lab research",
  "Science communication",
  "Technology ethics",

  // Society & Culture
  "Social media impact",
  "Digital privacy",
  "Cultural diversity",
  "Gender equality",
  "Human rights",
  "Community building",
  "Urban development",
  "Immigration",
  "Religious diversity",
  "Pop culture",
  "Arts and creativity",
  "Film and media",
  "Music industry",
  "Social activism",
  "Generational differences",
  "Family dynamics",
  "Volunteerism",
  "Language and communication",
  "Political engagement",
  "Media literacy",

  // Finance & Personal Development
  "Personal finance",
  "Budgeting",
  "Cryptocurrency",
  "Stock market",
  "Real estate",
  "Passive income",
  "Debt management",
  "Retirement planning",
  "Self-improvement",
  "Goal setting",
  "Emotional intelligence",
  "Time management",
  "Habit formation",
  "Confidence building",
  "Public speaking",
  "Networking",
  "Career development",
  "Job searching",
  "Resume writing",
  "Professional growth",

  // Travel & Lifestyle
  "Adventure travel",
  "Cultural tourism",
  "Budget travel",
  "Sustainable travel",
  "Travel photography",
  "Food culture",
  "Home decor",
  "Minimalism",
  "Fashion trends",
  "Beauty and skincare",
  "Parenting",
  "Relationships",
  "Hobbies and crafts",
  "Gaming culture",
  "Sports science",
  "Outdoor activities",
  "Pet care",
  "Book culture",
  "Cooking and recipes",
  "Interior design",
];

module.exports = KEYWORD_LIST;